CREATE TABLE "dictionary_generation_provider_circuit" (
	"consecutive_failures" integer DEFAULT 0 NOT NULL,
	"id" text PRIMARY KEY NOT NULL,
	"open_until" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dictionary_generation_provider_circuit_singleton" CHECK ("dictionary_generation_provider_circuit"."id" = 'single-card:v1'),
	CONSTRAINT "dictionary_generation_provider_circuit_failures" CHECK ("dictionary_generation_provider_circuit"."consecutive_failures" >= 0)
);
--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD COLUMN "provider_actual_cost_micros" integer;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD COLUMN "provider_actual_input_tokens" integer;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD COLUMN "provider_actual_output_tokens" integer;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD COLUMN "provider_reservation_settled_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD COLUMN "provider_reservation_state" text DEFAULT 'released' NOT NULL;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD COLUMN "provider_reserved_cost_micros" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD COLUMN "provider_reserved_input_tokens" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD COLUMN "provider_reserved_output_tokens" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD CONSTRAINT "dictionary_generation_jobs_provider_reservation" CHECK ("dictionary_generation_jobs"."provider_reservation_state" in ('active', 'settled', 'released') and "dictionary_generation_jobs"."provider_reserved_input_tokens" >= 0 and "dictionary_generation_jobs"."provider_reserved_output_tokens" >= 0 and "dictionary_generation_jobs"."provider_reserved_cost_micros" >= 0 and ("dictionary_generation_jobs"."provider_actual_input_tokens" is null or "dictionary_generation_jobs"."provider_actual_input_tokens" >= 0) and ("dictionary_generation_jobs"."provider_actual_output_tokens" is null or "dictionary_generation_jobs"."provider_actual_output_tokens" >= 0) and ("dictionary_generation_jobs"."provider_actual_cost_micros" is null or "dictionary_generation_jobs"."provider_actual_cost_micros" >= 0) and (("dictionary_generation_jobs"."provider_reservation_state" = 'active' and "dictionary_generation_jobs"."provider_reserved_input_tokens" > 0 and "dictionary_generation_jobs"."provider_reserved_output_tokens" > 0 and "dictionary_generation_jobs"."provider_reserved_cost_micros" > 0 and "dictionary_generation_jobs"."provider_reservation_settled_at" is null and "dictionary_generation_jobs"."provider_actual_input_tokens" is null and "dictionary_generation_jobs"."provider_actual_output_tokens" is null and "dictionary_generation_jobs"."provider_actual_cost_micros" is null) or ("dictionary_generation_jobs"."provider_reservation_state" in ('settled', 'released') and "dictionary_generation_jobs"."provider_reservation_settled_at" is not null and "dictionary_generation_jobs"."provider_actual_input_tokens" is not null and "dictionary_generation_jobs"."provider_actual_output_tokens" is not null and "dictionary_generation_jobs"."provider_actual_cost_micros" is not null) or ("dictionary_generation_jobs"."provider_reservation_state" = 'released' and "dictionary_generation_jobs"."provider_reservation_settled_at" is null and "dictionary_generation_jobs"."provider_reserved_input_tokens" = 0 and "dictionary_generation_jobs"."provider_reserved_output_tokens" = 0 and "dictionary_generation_jobs"."provider_reserved_cost_micros" = 0)));