ALTER TABLE "dictionary_generation_jobs" DROP CONSTRAINT "dictionary_generation_jobs_kind_card";--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" DROP CONSTRAINT "dictionary_generation_jobs_provider_policy";--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" DROP CONSTRAINT "dictionary_generation_proposals_payload_state";--> statement-breakpoint
ALTER TABLE "dictionary_generation_provider_circuit" DROP CONSTRAINT "dictionary_generation_provider_circuit_singleton";--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" ADD COLUMN "accepted_batch_outcome" jsonb;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD CONSTRAINT "dictionary_generation_jobs_kind_card" CHECK (("dictionary_generation_jobs"."kind" = 'single-card' and "dictionary_generation_jobs"."card_id" is not null and "dictionary_generation_jobs"."expected_card_version" is not null) or ("dictionary_generation_jobs"."kind" <> 'single-card' and "dictionary_generation_jobs"."card_id" is null and "dictionary_generation_jobs"."expected_card_version" is null));--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD CONSTRAINT "dictionary_generation_jobs_provider_policy" CHECK ("dictionary_generation_jobs"."provider_max_input_tokens_per_attempt" between 32768 and 262144 and "dictionary_generation_jobs"."provider_max_output_tokens_per_attempt" between 128 and 40960 and "dictionary_generation_jobs"."provider_input_cost_micros_per_million_tokens" between 0 and 1000000000 and "dictionary_generation_jobs"."provider_output_cost_micros_per_million_tokens" between 0 and 1000000000 and "dictionary_generation_jobs"."provider_max_cost_micros_per_attempt" between 1 and 10000000 and "dictionary_generation_jobs"."provider_max_cost_micros_per_attempt" >= (((("dictionary_generation_jobs"."provider_max_input_tokens_per_attempt")::bigint * "dictionary_generation_jobs"."provider_input_cost_micros_per_million_tokens") + 999999) / 1000000) + (((("dictionary_generation_jobs"."provider_max_output_tokens_per_attempt")::bigint * "dictionary_generation_jobs"."provider_output_cost_micros_per_million_tokens") + 999999) / 1000000));--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" ADD CONSTRAINT "dictionary_generation_proposals_payload_state" CHECK (("dictionary_generation_proposals"."review_state" = 'reviewable' and "dictionary_generation_proposals"."payload" is not null and "dictionary_generation_proposals"."terminal_at" is null and "dictionary_generation_proposals"."accepted_candidate_fingerprint" is null and "dictionary_generation_proposals"."accepted_card_version" is null and "dictionary_generation_proposals"."accepted_dictionary_version" is null and "dictionary_generation_proposals"."accepted_revision_id" is null and "dictionary_generation_proposals"."accepted_batch_outcome" is null) or ("dictionary_generation_proposals"."review_state" = 'accepted' and "dictionary_generation_proposals"."payload" is null and "dictionary_generation_proposals"."terminal_at" is not null and ((
                "dictionary_generation_proposals"."accepted_candidate_fingerprint" is not null and
                "dictionary_generation_proposals"."accepted_card_version" is not null and
                "dictionary_generation_proposals"."accepted_dictionary_version" is not null and
                "dictionary_generation_proposals"."accepted_revision_id" is not null and
                "dictionary_generation_proposals"."accepted_batch_outcome" is null
            ) or (
                "dictionary_generation_proposals"."accepted_candidate_fingerprint" is not null and
                "dictionary_generation_proposals"."accepted_card_version" is null and
                "dictionary_generation_proposals"."accepted_dictionary_version" is null and
                "dictionary_generation_proposals"."accepted_revision_id" is null and
                "dictionary_generation_proposals"."accepted_batch_outcome" is not null
            ))) or ("dictionary_generation_proposals"."review_state" in ('discarded', 'expired') and "dictionary_generation_proposals"."payload" is null and "dictionary_generation_proposals"."terminal_at" is not null and "dictionary_generation_proposals"."accepted_candidate_fingerprint" is null and "dictionary_generation_proposals"."accepted_card_version" is null and "dictionary_generation_proposals"."accepted_dictionary_version" is null and "dictionary_generation_proposals"."accepted_revision_id" is null and "dictionary_generation_proposals"."accepted_batch_outcome" is null));--> statement-breakpoint
ALTER TABLE "dictionary_generation_provider_circuit" ADD CONSTRAINT "dictionary_generation_provider_circuit_format" CHECK (char_length("dictionary_generation_provider_circuit"."id") between 3 and 64 and "dictionary_generation_provider_circuit"."id" ~ '^[a-z][a-z0-9-]*:v[1-9][0-9]*$');