CREATE TABLE "dictionary_document_extractions" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"failure_unit_count" integer DEFAULT 0 NOT NULL,
	"job_id" uuid PRIMARY KEY NOT NULL,
	"observed_unit_count" integer NOT NULL,
	"payload" jsonb,
	"payload_fingerprint" text NOT NULL,
	"proposal_job_id" uuid,
	"redacted_at" timestamp with time zone,
	"schema_version" integer DEFAULT 1 NOT NULL,
	"state" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"upload_id" uuid NOT NULL,
	"valid_unit_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "dictionary_document_extractions_upload_unique" UNIQUE("upload_id"),
	CONSTRAINT "dictionary_document_extractions_schema" CHECK ("dictionary_document_extractions"."schema_version" = 1),
	CONSTRAINT "dictionary_document_extractions_counts" CHECK ("dictionary_document_extractions"."observed_unit_count" between 0 and 101 and "dictionary_document_extractions"."valid_unit_count" between 0 and 100 and "dictionary_document_extractions"."failure_unit_count" between 0 and 100 and (("dictionary_document_extractions"."state" in ('ready', 'proposed', 'redacted') and "dictionary_document_extractions"."observed_unit_count" between 1 and 100 and "dictionary_document_extractions"."valid_unit_count" + "dictionary_document_extractions"."failure_unit_count" = "dictionary_document_extractions"."observed_unit_count") or ("dictionary_document_extractions"."state" = 'no_terms_found' and "dictionary_document_extractions"."observed_unit_count" = 0 and "dictionary_document_extractions"."valid_unit_count" = 0 and "dictionary_document_extractions"."failure_unit_count" = 0) or ("dictionary_document_extractions"."state" = 'too_many_terms' and "dictionary_document_extractions"."observed_unit_count" = 101 and "dictionary_document_extractions"."valid_unit_count" = 0 and "dictionary_document_extractions"."failure_unit_count" = 0))),
	CONSTRAINT "dictionary_document_extractions_payload_state" CHECK (("dictionary_document_extractions"."state" = 'ready' and "dictionary_document_extractions"."payload" is not null and jsonb_typeof("dictionary_document_extractions"."payload") = 'object' and pg_column_size("dictionary_document_extractions"."payload") <= 2097152 and "dictionary_document_extractions"."proposal_job_id" is null and "dictionary_document_extractions"."redacted_at" is null) or ("dictionary_document_extractions"."state" = 'proposed' and "dictionary_document_extractions"."payload" is null and "dictionary_document_extractions"."proposal_job_id" = "dictionary_document_extractions"."job_id" and "dictionary_document_extractions"."redacted_at" is not null) or ("dictionary_document_extractions"."state" in ('redacted', 'no_terms_found', 'too_many_terms') and "dictionary_document_extractions"."payload" is null and "dictionary_document_extractions"."proposal_job_id" is null and "dictionary_document_extractions"."redacted_at" is not null)),
	CONSTRAINT "dictionary_document_extractions_fingerprint" CHECK (char_length("dictionary_document_extractions"."payload_fingerprint") between 58 and 64 and "dictionary_document_extractions"."payload_fingerprint" ~ '^hmac-sha256:v[1-9][0-9]*:[A-Za-z0-9_-]{43}$'),
	CONSTRAINT "dictionary_document_extractions_timestamps" CHECK ("dictionary_document_extractions"."updated_at" >= "dictionary_document_extractions"."created_at" and ("dictionary_document_extractions"."redacted_at" is null or "dictionary_document_extractions"."redacted_at" >= "dictionary_document_extractions"."created_at"))
);
--> statement-breakpoint
CREATE TABLE "dictionary_document_object_versions" (
	"checksum_sha256" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"id" uuid PRIMARY KEY NOT NULL,
	"is_current" boolean DEFAULT false NOT NULL,
	"kind" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"storage_version_id" text NOT NULL,
	"upload_id" uuid NOT NULL,
	CONSTRAINT "dictionary_document_object_versions_storage_unique" UNIQUE("upload_id","storage_version_id"),
	CONSTRAINT "dictionary_document_object_versions_identity" CHECK (char_length("dictionary_document_object_versions"."storage_version_id") between 1 and 1024 and "dictionary_document_object_versions"."storage_version_id" !~ '[[:cntrl:]]' and "dictionary_document_object_versions"."checksum_sha256" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "dictionary_document_object_versions_kind_size" CHECK (("dictionary_document_object_versions"."kind" = 'data' and "dictionary_document_object_versions"."size_bytes" > 0) or ("dictionary_document_object_versions"."kind" = 'tombstone' and "dictionary_document_object_versions"."size_bytes" = 0)),
	CONSTRAINT "dictionary_document_object_versions_lifecycle" CHECK (("dictionary_document_object_versions"."deleted_at" is null or "dictionary_document_object_versions"."deleted_at" >= "dictionary_document_object_versions"."created_at") and ("dictionary_document_object_versions"."is_current" = false or "dictionary_document_object_versions"."deleted_at" is null))
);
--> statement-breakpoint
CREATE TABLE "dictionary_document_uploads" (
	"accounted_physical_bytes" bigint NOT NULL,
	"capability_expires_at" timestamp with time zone NOT NULL,
	"cleanup_attempt_count" integer DEFAULT 0 NOT NULL,
	"cleanup_completed_at" timestamp with time zone,
	"cleanup_failure_category" text,
	"cleanup_fencing_token" bigint DEFAULT 0 NOT NULL,
	"cleanup_heartbeat_at" timestamp with time zone,
	"cleanup_lease_deadline" timestamp with time zone,
	"cleanup_next_attempt_at" timestamp with time zone NOT NULL,
	"cleanup_state" text DEFAULT 'inactive' NOT NULL,
	"cleanup_worker_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"data_versions_deleted_at" timestamp with time zone,
	"detected_format" text,
	"dictionary_id" uuid NOT NULL,
	"expected_checksum_sha256" text NOT NULL,
	"expected_content_type" text NOT NULL,
	"expected_format" text NOT NULL,
	"expected_size_bytes" bigint NOT NULL,
	"id" uuid PRIMARY KEY NOT NULL,
	"job_id" uuid NOT NULL,
	"object_key" text NOT NULL,
	"observed_physical_bytes" bigint DEFAULT 0 NOT NULL,
	"owner_id" uuid NOT NULL,
	"processing_state" text DEFAULT 'authorized' NOT NULL,
	"quota_released_at" timestamp with time zone,
	"scan_completed_at" timestamp with time zone,
	"scanner_engine_version" text,
	"scanner_outcome" text,
	"scanner_signature_updated_at" timestamp with time zone,
	"scanner_signature_version" text,
	"schema_version" integer DEFAULT 1 NOT NULL,
	"terminal_at" timestamp with time zone,
	"tombstone_created_at" timestamp with time zone,
	"tombstone_storage_version_id" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"upload_completed_at" timestamp with time zone,
	"verified_checksum_sha256" text,
	"verified_size_bytes" bigint,
	"verified_storage_version_id" text,
	CONSTRAINT "dictionary_document_uploads_job_unique" UNIQUE("job_id"),
	CONSTRAINT "dictionary_document_uploads_job_id_unique" UNIQUE("job_id","id"),
	CONSTRAINT "dictionary_document_uploads_object_key_unique" UNIQUE("object_key"),
	CONSTRAINT "dictionary_document_uploads_schema" CHECK ("dictionary_document_uploads"."schema_version" = 1),
	CONSTRAINT "dictionary_document_uploads_object_key" CHECK (char_length("dictionary_document_uploads"."object_key") between 16 and 512 and "dictionary_document_uploads"."object_key" ~ '^[A-Za-z0-9/_-]+$'),
	CONSTRAINT "dictionary_document_uploads_expected_file" CHECK ("dictionary_document_uploads"."expected_format" in ('txt', 'markdown', 'docx', 'pdf', 'png', 'jpeg', 'webp') and char_length("dictionary_document_uploads"."expected_content_type") between 1 and 255 and "dictionary_document_uploads"."expected_content_type" !~ '[[:cntrl:]]' and "dictionary_document_uploads"."expected_size_bytes" between 1 and 20971520 and "dictionary_document_uploads"."expected_checksum_sha256" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "dictionary_document_uploads_verified_file" CHECK (("dictionary_document_uploads"."upload_completed_at" is null and "dictionary_document_uploads"."verified_storage_version_id" is null and "dictionary_document_uploads"."verified_size_bytes" is null and "dictionary_document_uploads"."verified_checksum_sha256" is null and "dictionary_document_uploads"."detected_format" is null) or ("dictionary_document_uploads"."upload_completed_at" is not null and "dictionary_document_uploads"."verified_storage_version_id" is not null and char_length("dictionary_document_uploads"."verified_storage_version_id") between 1 and 1024 and "dictionary_document_uploads"."verified_storage_version_id" !~ '[[:cntrl:]]' and "dictionary_document_uploads"."verified_size_bytes" = "dictionary_document_uploads"."expected_size_bytes" and "dictionary_document_uploads"."verified_checksum_sha256" = "dictionary_document_uploads"."expected_checksum_sha256" and "dictionary_document_uploads"."detected_format" in ('txt', 'markdown', 'docx', 'pdf', 'png', 'jpeg', 'webp'))),
	CONSTRAINT "dictionary_document_uploads_processing_state" CHECK ("dictionary_document_uploads"."processing_state" in ('authorized', 'quarantined', 'scanning', 'clean', 'extracting', 'cleaning', 'proposed', 'rejected', 'failed', 'cancelled', 'expired') and (("dictionary_document_uploads"."processing_state" = 'authorized' and "dictionary_document_uploads"."upload_completed_at" is null) or ("dictionary_document_uploads"."processing_state" in ('failed', 'cancelled', 'expired')) or ("dictionary_document_uploads"."processing_state" not in ('authorized', 'failed', 'cancelled', 'expired') and "dictionary_document_uploads"."upload_completed_at" is not null)) and (("dictionary_document_uploads"."processing_state" in ('proposed', 'rejected', 'failed', 'cancelled', 'expired')) = ("dictionary_document_uploads"."terminal_at" is not null))),
	CONSTRAINT "dictionary_document_uploads_scan" CHECK ((("dictionary_document_uploads"."scanner_outcome" is null and "dictionary_document_uploads"."scan_completed_at" is null and "dictionary_document_uploads"."scanner_engine_version" is null and "dictionary_document_uploads"."scanner_signature_version" is null and "dictionary_document_uploads"."scanner_signature_updated_at" is null) or ("dictionary_document_uploads"."scanner_outcome" in ('clean', 'infected', 'unavailable', 'timeout', 'limit_exceeded', 'invalid_response', 'stale_signatures') and "dictionary_document_uploads"."scan_completed_at" is not null and (("dictionary_document_uploads"."scanner_engine_version" is null and "dictionary_document_uploads"."scanner_signature_version" is null and "dictionary_document_uploads"."scanner_signature_updated_at" is null and "dictionary_document_uploads"."scanner_outcome" in ('unavailable', 'timeout', 'invalid_response')) or ("dictionary_document_uploads"."scanner_engine_version" is not null and char_length("dictionary_document_uploads"."scanner_engine_version") between 1 and 128 and "dictionary_document_uploads"."scanner_signature_version" is not null and char_length("dictionary_document_uploads"."scanner_signature_version") between 1 and 128 and "dictionary_document_uploads"."scanner_signature_updated_at" is not null and "dictionary_document_uploads"."scanner_signature_updated_at" <= "dictionary_document_uploads"."scan_completed_at")))) and ("dictionary_document_uploads"."processing_state" not in ('clean', 'extracting', 'cleaning', 'proposed') or "dictionary_document_uploads"."scanner_outcome" = 'clean')),
	CONSTRAINT "dictionary_document_uploads_quota" CHECK ("dictionary_document_uploads"."observed_physical_bytes" >= 0 and "dictionary_document_uploads"."accounted_physical_bytes" >= "dictionary_document_uploads"."expected_size_bytes" and "dictionary_document_uploads"."accounted_physical_bytes" >= "dictionary_document_uploads"."observed_physical_bytes" and (("dictionary_document_uploads"."cleanup_state" in ('waiting_capability_expiry', 'complete')) = ("dictionary_document_uploads"."quota_released_at" is not null)) and ("dictionary_document_uploads"."quota_released_at" is null or ("dictionary_document_uploads"."data_versions_deleted_at" is not null and "dictionary_document_uploads"."quota_released_at" >= "dictionary_document_uploads"."data_versions_deleted_at"))),
	CONSTRAINT "dictionary_document_uploads_cleanup_state" CHECK ("dictionary_document_uploads"."cleanup_state" in ('inactive', 'pending', 'running', 'waiting_capability_expiry', 'complete') and "dictionary_document_uploads"."cleanup_attempt_count" between 0 and 100 and "dictionary_document_uploads"."cleanup_fencing_token" >= 0 and ("dictionary_document_uploads"."cleanup_failure_category" is null or "dictionary_document_uploads"."cleanup_failure_category" ~ '^[a-z][a-z0-9_]{0,63}$') and (("dictionary_document_uploads"."cleanup_state" = 'running' and "dictionary_document_uploads"."cleanup_worker_id" is not null and char_length("dictionary_document_uploads"."cleanup_worker_id") between 1 and 128 and "dictionary_document_uploads"."cleanup_lease_deadline" is not null and "dictionary_document_uploads"."cleanup_heartbeat_at" is not null) or ("dictionary_document_uploads"."cleanup_state" <> 'running' and "dictionary_document_uploads"."cleanup_worker_id" is null and "dictionary_document_uploads"."cleanup_lease_deadline" is null and "dictionary_document_uploads"."cleanup_heartbeat_at" is null))),
	CONSTRAINT "dictionary_document_uploads_cleanup_outcome" CHECK (("dictionary_document_uploads"."tombstone_storage_version_id" is null) = ("dictionary_document_uploads"."tombstone_created_at" is null) and ("dictionary_document_uploads"."tombstone_storage_version_id" is null or (char_length("dictionary_document_uploads"."tombstone_storage_version_id") between 1 and 1024 and "dictionary_document_uploads"."tombstone_storage_version_id" !~ '[[:cntrl:]]')) and ("dictionary_document_uploads"."data_versions_deleted_at" is null or "dictionary_document_uploads"."tombstone_created_at" is not null) and (("dictionary_document_uploads"."cleanup_state" = 'waiting_capability_expiry' and "dictionary_document_uploads"."tombstone_created_at" is not null and "dictionary_document_uploads"."data_versions_deleted_at" is not null and "dictionary_document_uploads"."cleanup_completed_at" is null) or ("dictionary_document_uploads"."cleanup_state" = 'complete' and "dictionary_document_uploads"."tombstone_created_at" is not null and "dictionary_document_uploads"."data_versions_deleted_at" is not null and "dictionary_document_uploads"."cleanup_completed_at" is not null and "dictionary_document_uploads"."cleanup_completed_at" >= "dictionary_document_uploads"."capability_expires_at") or "dictionary_document_uploads"."cleanup_state" in ('inactive', 'pending', 'running'))),
	CONSTRAINT "dictionary_document_uploads_timestamps" CHECK ("dictionary_document_uploads"."capability_expires_at" > "dictionary_document_uploads"."created_at" and "dictionary_document_uploads"."capability_expires_at" <= "dictionary_document_uploads"."created_at" + interval '1 hour' and "dictionary_document_uploads"."cleanup_next_attempt_at" >= "dictionary_document_uploads"."created_at" and "dictionary_document_uploads"."updated_at" >= "dictionary_document_uploads"."created_at" and ("dictionary_document_uploads"."upload_completed_at" is null or "dictionary_document_uploads"."upload_completed_at" >= "dictionary_document_uploads"."created_at") and ("dictionary_document_uploads"."scan_completed_at" is null or "dictionary_document_uploads"."scan_completed_at" >= "dictionary_document_uploads"."created_at") and ("dictionary_document_uploads"."terminal_at" is null or "dictionary_document_uploads"."terminal_at" >= "dictionary_document_uploads"."created_at") and ("dictionary_document_uploads"."cleanup_heartbeat_at" is null or "dictionary_document_uploads"."cleanup_heartbeat_at" >= "dictionary_document_uploads"."created_at") and ("dictionary_document_uploads"."cleanup_lease_deadline" is null or ("dictionary_document_uploads"."cleanup_heartbeat_at" is not null and "dictionary_document_uploads"."cleanup_lease_deadline" > "dictionary_document_uploads"."cleanup_heartbeat_at")) and ("dictionary_document_uploads"."tombstone_created_at" is null or "dictionary_document_uploads"."tombstone_created_at" >= "dictionary_document_uploads"."created_at") and ("dictionary_document_uploads"."data_versions_deleted_at" is null or "dictionary_document_uploads"."data_versions_deleted_at" >= "dictionary_document_uploads"."tombstone_created_at") and ("dictionary_document_uploads"."cleanup_completed_at" is null or "dictionary_document_uploads"."cleanup_completed_at" >= "dictionary_document_uploads"."created_at") and ("dictionary_document_uploads"."quota_released_at" is null or "dictionary_document_uploads"."quota_released_at" >= "dictionary_document_uploads"."created_at"))
);
--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" DROP CONSTRAINT "dictionary_generation_jobs_progress";--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" DROP CONSTRAINT "dictionary_generation_jobs_timestamps";--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" DROP CONSTRAINT "dictionary_generation_proposals_timestamps";--> statement-breakpoint
DROP INDEX "dictionary_generation_jobs_claim_idx";--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD COLUMN "awaiting_upload_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" ADD COLUMN "document_published_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" ADD COLUMN "document_staged_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" ADD COLUMN "staged_provider_cost_micros" integer;--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" ADD COLUMN "staged_provider_input_tokens" integer;--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" ADD COLUMN "staged_provider_output_tokens" integer;--> statement-breakpoint
ALTER TABLE "dictionary_document_extractions" ADD CONSTRAINT "dictionary_document_extractions_proposal_job_id_dictionary_generation_proposals_job_id_fk" FOREIGN KEY ("proposal_job_id") REFERENCES "public"."dictionary_generation_proposals"("job_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dictionary_document_extractions" ADD CONSTRAINT "dictionary_document_extractions_upload_job_fk" FOREIGN KEY ("job_id","upload_id") REFERENCES "public"."dictionary_document_uploads"("job_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dictionary_document_object_versions" ADD CONSTRAINT "dictionary_document_object_versions_upload_id_dictionary_document_uploads_id_fk" FOREIGN KEY ("upload_id") REFERENCES "public"."dictionary_document_uploads"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dictionary_document_uploads" ADD CONSTRAINT "dictionary_document_uploads_job_id_dictionary_generation_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."dictionary_generation_jobs"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dictionary_document_uploads" ADD CONSTRAINT "dictionary_document_uploads_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dictionary_document_uploads" ADD CONSTRAINT "dictionary_document_uploads_dictionary_owner_fk" FOREIGN KEY ("dictionary_id","owner_id") REFERENCES "public"."dictionaries"("id","owner_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "dictionary_document_extractions_payload_expiry_idx" ON "dictionary_document_extractions" USING btree ("created_at","job_id") WHERE "dictionary_document_extractions"."payload" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "dictionary_document_object_versions_one_current" ON "dictionary_document_object_versions" USING btree ("upload_id") WHERE "dictionary_document_object_versions"."is_current" = true;--> statement-breakpoint
CREATE INDEX "dictionary_document_object_versions_active_bytes_idx" ON "dictionary_document_object_versions" USING btree ("upload_id","kind","size_bytes") WHERE "dictionary_document_object_versions"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX "dictionary_document_uploads_owner_quota_idx" ON "dictionary_document_uploads" USING btree ("owner_id","created_at","id") WHERE "dictionary_document_uploads"."quota_released_at" is null;--> statement-breakpoint
CREATE INDEX "dictionary_document_uploads_cleanup_claim_idx" ON "dictionary_document_uploads" USING btree ("cleanup_state","cleanup_next_attempt_at","created_at","id") WHERE "dictionary_document_uploads"."cleanup_state" in ('pending', 'waiting_capability_expiry');--> statement-breakpoint
CREATE INDEX "dictionary_document_uploads_cleanup_lease_idx" ON "dictionary_document_uploads" USING btree ("cleanup_lease_deadline") WHERE "dictionary_document_uploads"."cleanup_state" = 'running';--> statement-breakpoint
CREATE INDEX "dictionary_document_uploads_capability_expiry_idx" ON "dictionary_document_uploads" USING btree ("capability_expires_at","id") WHERE "dictionary_document_uploads"."processing_state" = 'authorized';--> statement-breakpoint
CREATE INDEX "dictionary_generation_jobs_claim_idx" ON "dictionary_generation_jobs" USING btree ("execution_state","next_attempt_at","created_at","id") WHERE "dictionary_generation_jobs"."awaiting_upload_at" is null;--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD CONSTRAINT "dictionary_generation_jobs_upload_wait" CHECK ("dictionary_generation_jobs"."awaiting_upload_at" is null or ("dictionary_generation_jobs"."kind" = 'document-terms' and "dictionary_generation_jobs"."format" = 'document-terms:v1' and "dictionary_generation_jobs"."execution_state" = 'queued' and "dictionary_generation_jobs"."progress_stage" = 'awaiting_upload' and "dictionary_generation_jobs"."progress_percent" = 0 and "dictionary_generation_jobs"."provider_reservation_state" = 'released' and "dictionary_generation_jobs"."provider_reserved_input_tokens" = 0 and "dictionary_generation_jobs"."provider_reserved_output_tokens" = 0 and "dictionary_generation_jobs"."provider_reserved_cost_micros" = 0 and "dictionary_generation_jobs"."provider_reservation_settled_at" is null));--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD CONSTRAINT "dictionary_generation_jobs_progress" CHECK ("dictionary_generation_jobs"."progress_percent" between 0 and 100 and "dictionary_generation_jobs"."progress_stage" in ('awaiting_upload', 'queued', 'scanning', 'extracting', 'ocr', 'generating', 'validating', 'cleaning', 'review_ready', 'terminal'));--> statement-breakpoint
ALTER TABLE "dictionary_generation_jobs" ADD CONSTRAINT "dictionary_generation_jobs_timestamps" CHECK ("dictionary_generation_jobs"."updated_at" >= "dictionary_generation_jobs"."created_at" and "dictionary_generation_jobs"."next_attempt_at" >= "dictionary_generation_jobs"."created_at" and ("dictionary_generation_jobs"."awaiting_upload_at" is null or "dictionary_generation_jobs"."awaiting_upload_at" >= "dictionary_generation_jobs"."created_at") and ("dictionary_generation_jobs"."completed_at" is null or "dictionary_generation_jobs"."completed_at" >= "dictionary_generation_jobs"."created_at") and ("dictionary_generation_jobs"."cancellation_requested_at" is null or "dictionary_generation_jobs"."cancellation_requested_at" >= "dictionary_generation_jobs"."created_at") and ("dictionary_generation_jobs"."heartbeat_at" is null or "dictionary_generation_jobs"."heartbeat_at" >= "dictionary_generation_jobs"."created_at") and ("dictionary_generation_jobs"."lease_deadline" is null or ("dictionary_generation_jobs"."heartbeat_at" is not null and "dictionary_generation_jobs"."lease_deadline" > "dictionary_generation_jobs"."heartbeat_at")));--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" ADD CONSTRAINT "dictionary_generation_proposals_document_publication" CHECK (("dictionary_generation_proposals"."document_staged_at" is null and "dictionary_generation_proposals"."document_published_at" is null and "dictionary_generation_proposals"."staged_provider_input_tokens" is null and "dictionary_generation_proposals"."staged_provider_output_tokens" is null and "dictionary_generation_proposals"."staged_provider_cost_micros" is null) or ("dictionary_generation_proposals"."document_staged_at" is not null and "dictionary_generation_proposals"."staged_provider_input_tokens" is not null and "dictionary_generation_proposals"."staged_provider_input_tokens" between 0 and 2621440 and "dictionary_generation_proposals"."staged_provider_output_tokens" is not null and "dictionary_generation_proposals"."staged_provider_output_tokens" between 0 and 409600 and "dictionary_generation_proposals"."staged_provider_cost_micros" is not null and "dictionary_generation_proposals"."staged_provider_cost_micros" between 0 and 100000000 and ("dictionary_generation_proposals"."document_published_at" is null or "dictionary_generation_proposals"."document_published_at" >= "dictionary_generation_proposals"."document_staged_at") and ("dictionary_generation_proposals"."document_published_at" is not null or "dictionary_generation_proposals"."review_state" <> 'accepted')));--> statement-breakpoint
ALTER TABLE "dictionary_generation_proposals" ADD CONSTRAINT "dictionary_generation_proposals_timestamps" CHECK ("dictionary_generation_proposals"."expires_at" > "dictionary_generation_proposals"."created_at" and "dictionary_generation_proposals"."updated_at" >= "dictionary_generation_proposals"."created_at" and ("dictionary_generation_proposals"."document_staged_at" is null or "dictionary_generation_proposals"."document_staged_at" >= "dictionary_generation_proposals"."created_at") and ("dictionary_generation_proposals"."document_published_at" is null or "dictionary_generation_proposals"."document_published_at" >= "dictionary_generation_proposals"."created_at") and ("dictionary_generation_proposals"."terminal_at" is null or "dictionary_generation_proposals"."terminal_at" >= "dictionary_generation_proposals"."created_at"));